# Generated by Django 5.2.6 on 2025-09-30 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detectionmodelresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_filename', models.CharField(default='unknown_video.mp4', max_length=255)),
                ('missing_person_name', models.CharField(default='Unknown', max_length=255)),
                ('found', models.BooleanField(default=False)),
                ('frames_detected', models.TextField(default='[]')),
                ('total_frames', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Missingperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='missing_person/')),
                ('description', models.TextField(blank=True)),
                ('date_repo', models.DateField(auto_now_add=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
